const fs = require('fs');
const path = require('path');

const contractsOutDir = path.join(__dirname, '../packages/contracts/out');
const sharedSrcDir = path.join(__dirname, '../packages/shared/src');

function syncAbis() {
  if (!fs.existsSync(contractsOutDir)) {
    console.warn('Contracts out directory not found. Please compile contracts first.');
    return;
  }

  // Example: extracting ABI from a compiled contract
  // Note: This is a simplified script that needs to match actual Foundry output structure
  // For Rita, we assume a RitaModule.sol output exists
  
  const files = ['RitaModule.sol/RitaModule.json']; // Add your actual compiled contract json paths here
  
  let exportsContent = `// Auto-generated by sync-abis.js\n\n`;

  files.forEach(file => {
    const fullPath = path.join(contractsOutDir, file);
    if (fs.existsSync(fullPath)) {
      const compiled = require(fullPath);
      const abi = compiled.abi;
      const contractName = file.split('/')[0].replace('.sol', '');
      
      exportsContent += `export const ${contractName}ABI = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
      console.log(`Synced ABI for ${contractName}`);
    }
  });

  const indexPath = path.join(sharedSrcDir, 'abis.ts');
  fs.writeFileSync(indexPath, exportsContent);
  console.log('ABI sync complete.');
}

syncAbis();
